// Publish the accepted proof's exact assets, not a second hand-built theme.
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import path from 'node:path';
import { validateBrowserModule } from './extract-surfaces.mjs';
import { prepareDemo, projectRoot, toolsRoot, digest } from './build.mjs';

const { outputRoot, proof, templates } = await prepareDemo();
const target = path.join(projectRoot, 'public/original-player');
const generated = path.join(projectRoot, 'src/features/streaming/generated/accepted');
await mkdir(path.join(target, 'assets'), { recursive: true });
await mkdir(generated, { recursive: true });
const files = new Map();
async function publish(name, bytes) {
  if (name.endsWith('.js')) validateBrowserModule(bytes.toString('utf8'));
  await writeFile(path.join(target, name), bytes);
  files.set(name, { file: name, sha256: digest(bytes), bytes: bytes.length });
}
for (const asset of [...proof.originalFiles, ...proof.resourceFiles]) {
  const bytes = await readFile(path.join(outputRoot, asset.file));
  if (digest(bytes) !== asset.sha256) throw new Error(`Accepted asset changed: ${asset.file}`);
  await publish(asset.file, bytes);
}
for (const name of ['original-surfaces.js', 'original-messages.js', 'replay-search.js', 'replay-search.css', 'player-adaptations.css']) {
  const bytes = await readFile(path.join(outputRoot, name));
  await publish(name, bytes);
  if (name !== 'player-adaptations.css') await writeFile(path.join(generated, name), bytes);
}
await copyFile(path.join(toolsRoot, 'app-surfaces.d.ts'), path.join(generated, 'original-surfaces.d.ts'));
const localCss = (await readFile(path.join(outputRoot, 'local-index.css'), 'utf8')).replaceAll('url(/assets/', 'url(./assets/');
const vendorCss = await readFile(path.join(outputRoot, 'assets/vendor-DVDNLy6N.css'), 'utf8');
// Full original rules are retained. The main app must not inherit dormant web
// font fallbacks or unrelated sports images from that stylesheet. Resolve a
// cached equivalent where available; otherwise use an inert local data source.
const localizeUrls = (css, prefix) => css.replaceAll('url(./assets/', `url(${prefix}`)
  .replace(/url\((["']?)(https?:\/\/[^"')\s]+|\/\/[^"')\s]+)\1\)/gi, (_match, _quote, url) => {
    const name = path.posix.basename(new URL(url, 'https://unused.invalid').pathname);
    const local = [`assets/${name}`, `assets/${name.replace(/\.woff$/, '.woff2')}`].find(file => files.has(file));
    return local ? `url(${prefix}${path.posix.basename(local)})` : 'url("data:application/octet-stream;base64,")';
  });
await publish('local-index.css', Buffer.from(localizeUrls(localCss, './assets/')));
const appCss = localizeUrls(`${vendorCss}\n${localCss}`, '/original-player/assets/');
await writeFile(path.join(generated, 'original.css'), appCss);
await writeFile(path.join(generated, 'fonts.css'), (appCss.match(/@font-face\s*\{[^{}]*\}/g) || []).filter(rule => rule.includes('Nemony')).join('\n'));
await publish('recording-metadata.js', await readFile(path.join(toolsRoot, 'recording-metadata.js')));
await publish('accepted-vod-template.js', Buffer.from(`// Exact accepted VOD expression. See accepted-manifest.json.\nexport default ${JSON.stringify(templates.vod)};\n`));
await writeFile(path.join(target, 'accepted-manifest.json'), JSON.stringify({ format: 1, source: proof, files: [...files.values()], adaptations: 'Saved recording metadata uses the original header; no live badge or invented viewers. Local replay adapter retains session isolation, clocks and privacy.' }, null, 2));
const mime = file => file.endsWith('.js') ? 'text/javascript; charset=utf-8' : file.endsWith('.css') ? 'text/css; charset=utf-8' : file.endsWith('.woff2') ? 'font/woff2' : 'image/png';
const rust = `// Generated by tools/chzzk-offline-player/publish-app.mjs. Exact static routes only.\npub(super) fn asset(path: &str) -> Option<(&'static [u8], &'static str)> {\n    Some(match path {\n${[...files.keys()].sort().map(file => `        ${JSON.stringify('/' + file)} => (include_bytes!(${JSON.stringify('../../../public/original-player/' + file)}), ${JSON.stringify(mime(file))}),`).join('\n')}\n        _ => return None,\n    })\n}\n`;
await writeFile(path.join(projectRoot, 'src-tauri/src/streaming/accepted_player_assets.rs'), rust);
console.log(JSON.stringify({ published: files.size, originalAssets: proof.originalFiles.length + proof.resourceFiles.length, sourceNetworkUsed: false }));
