// Generated by tools/chzzk-offline-player/publish-app.mjs. Exact static routes only.
pub(super) fn asset(path: &str) -> Option<(&'static [u8], &'static str)> {
    Some(match path {
        "/accepted-vod-template.js" => (
            include_bytes!("../../../public/original-player/accepted-vod-template.js"),
            "text/javascript; charset=utf-8",
        ),
        "/assets/SDNemony2dBasicBd.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd0.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd0.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd1.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd1.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd10.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd10.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd100.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd100.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd101.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd101.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd102.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd102.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd103.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd103.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd104.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd104.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd105.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd105.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd106.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd106.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd107.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd107.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd108.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd108.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd109.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd109.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd11.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd11.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd110.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd110.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd111.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd111.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd112.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd112.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd113.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd113.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd114.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd114.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd115.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd115.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd116.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd116.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd117.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd117.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd118.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd118.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd119.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd119.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd12.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd12.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd13.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd13.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd14.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd14.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd15.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd15.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd16.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd16.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd17.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd17.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd18.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd18.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd19.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd19.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd2.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd2.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd20.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd20.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd21.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd21.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd22.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd22.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd23.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd23.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd24.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd24.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd25.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd25.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd26.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd26.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd27.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd27.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd28.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd28.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd29.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd29.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd3.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd3.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd30.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd30.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd31.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd31.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd32.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd32.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd33.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd33.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd34.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd34.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd35.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd35.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd36.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd36.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd37.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd37.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd38.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd38.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd39.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd39.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd4.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd4.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd40.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd40.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd41.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd41.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd42.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd42.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd43.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd43.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd44.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd44.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd45.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd45.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd46.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd46.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd47.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd47.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd48.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd48.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd49.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd49.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd5.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd5.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd50.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd50.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd51.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd51.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd52.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd52.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd53.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd53.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd54.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd54.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd55.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd55.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd56.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd56.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd57.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd57.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd58.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd58.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd59.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd59.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd6.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd6.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd60.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd60.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd61.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd61.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd62.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd62.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd63.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd63.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd64.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd64.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd65.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd65.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd66.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd66.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd67.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd67.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd68.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd68.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd69.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd69.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd7.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd7.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd70.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd70.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd71.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd71.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd72.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd72.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd73.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd73.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd74.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd74.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd75.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd75.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd76.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd76.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd77.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd77.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd78.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd78.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd79.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd79.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd8.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd8.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd80.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd80.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd81.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd81.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd82.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd82.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd83.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd83.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd84.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd84.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd85.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd85.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd86.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd86.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd87.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd87.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd88.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd88.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd89.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd89.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd9.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd9.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd90.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd90.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd91.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd91.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd92.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd92.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd93.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd93.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd94.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd94.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd95.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd95.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd96.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd96.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd97.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd97.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd98.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd98.woff2"),
            "font/woff2",
        ),
        "/assets/SDNemony2dBasicBd99.woff2" => (
            include_bytes!("../../../public/original-player/assets/SDNemony2dBasicBd99.woff2"),
            "font/woff2",
        ),
        "/assets/common-vendor-pcHQV1G2.js" => (
            include_bytes!("../../../public/original-player/assets/common-vendor-pcHQV1G2.js"),
            "text/javascript; charset=utf-8",
        ),
        "/assets/date-vendor-DhkCJ9xZ.js" => (
            include_bytes!("../../../public/original-player/assets/date-vendor-DhkCJ9xZ.js"),
            "text/javascript; charset=utf-8",
        ),
        "/assets/default_profile_dark.png" => (
            include_bytes!("../../../public/original-player/assets/default_profile_dark.png"),
            "image/png",
        ),
        "/assets/icon_official_mark.png" => (
            include_bytes!("../../../public/original-player/assets/icon_official_mark.png"),
            "image/png",
        ),
        "/assets/index-2Gtwn4qD.css" => (
            include_bytes!("../../../public/original-player/assets/index-2Gtwn4qD.css"),
            "text/css; charset=utf-8",
        ),
        "/assets/player-vendor-BYg0wCyN.js" => (
            include_bytes!("../../../public/original-player/assets/player-vendor-BYg0wCyN.js"),
            "text/javascript; charset=utf-8",
        ),
        "/assets/player-vendor-Ct4cRQDi.css" => (
            include_bytes!("../../../public/original-player/assets/player-vendor-Ct4cRQDi.css"),
            "text/css; charset=utf-8",
        ),
        "/assets/rolldown-runtime-CJJwijRH.js" => (
            include_bytes!("../../../public/original-player/assets/rolldown-runtime-CJJwijRH.js"),
            "text/javascript; charset=utf-8",
        ),
        "/assets/vendor-DQYi7KBW.js" => (
            include_bytes!("../../../public/original-player/assets/vendor-DQYi7KBW.js"),
            "text/javascript; charset=utf-8",
        ),
        "/assets/vendor-DVDNLy6N.css" => (
            include_bytes!("../../../public/original-player/assets/vendor-DVDNLy6N.css"),
            "text/css; charset=utf-8",
        ),
        "/local-index.css" => (
            include_bytes!("../../../public/original-player/local-index.css"),
            "text/css; charset=utf-8",
        ),
        "/original-messages.js" => (
            include_bytes!("../../../public/original-player/original-messages.js"),
            "text/javascript; charset=utf-8",
        ),
        "/original-surfaces.js" => (
            include_bytes!("../../../public/original-player/original-surfaces.js"),
            "text/javascript; charset=utf-8",
        ),
        "/player-adaptations.css" => (
            include_bytes!("../../../public/original-player/player-adaptations.css"),
            "text/css; charset=utf-8",
        ),
        "/recording-metadata.js" => (
            include_bytes!("../../../public/original-player/recording-metadata.js"),
            "text/javascript; charset=utf-8",
        ),
        "/replay-search.css" => (
            include_bytes!("../../../public/original-player/replay-search.css"),
            "text/css; charset=utf-8",
        ),
        "/replay-search.js" => (
            include_bytes!("../../../public/original-player/replay-search.js"),
            "text/javascript; charset=utf-8",
        ),
        _ => return None,
    })
}
